spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8000